### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jafrazie** [CiscoDevNet/ydk-py-samples#1]
"The have the following characteristics:" should be "They have the following characteristics:"

How are applications classified as basic vs. intermediate?

FYI, this is a dead link (bottom of page):
https://github.com/CiscoDevNet/ydk-py-samples/etree/master/samples/basic

**Comment by 111pontes** [comment]
Thanks, fixed the typos. As described in the README, basic apps focus on a single model and have no or minimal programming logic (conditionals, loops, etc). They should be your starting point if you don't have strong experience with models or with programming. They are grouped by model.
Intermediate apps may have some programming logic and combine more than one model. They are classified separately by use case.  You can expect a number of apps trickling in during the next following weeks.
