### ISSUE TITLE
vagrant problem

### ISSUE THREAD

**Issue by alwye** [CiscoDevNet/ydk-py-samples#9]
Hi -

been trying to spin up a vagrant box (a few times), it is not working properly:

ALZVEREV-M-X2U9:ydk-py-samples alzverev$ vagrant up
Bringing machine 'ydk-py-ubuntu' up with 'virtualbox' provider...
==> ydk-py-ubuntu: Box 'ydk-py-ubuntu' could not be found. Attempting to find and install...
    ydk-py-ubuntu: Box Provider: virtualbox
    ydk-py-ubuntu: Box Version: >= 0
==> ydk-py-ubuntu: Box file was not detected as metadata. Adding it directly...
==> ydk-py-ubuntu: Adding box 'ydk-py-ubuntu' (v0) for provider: virtualbox
    ydk-py-ubuntu: Downloading: http://ydk.cisco.com/vagrant/ydk-py-ubuntu/
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed to connect to ydk.cisco.com port 80: Operation timed out

**Comment by 111pontes** [comment]
Working on a resolution...

**Comment by 111pontes** [comment]
Fixed
